# Generated by Django 5.2.6 on 2025-10-26 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Main heading (leave blank to use default)', max_length=255, null=True)),
                ('subtitle', models.TextField(blank=True, help_text='Subtext (leave blank to use default)', null=True)),
                ('image', models.ImageField(blank=True, help_text='Hero background image', null=True, upload_to='hero_images/')),
                ('overlay_color', models.CharField(default='from-black/70 via-black/60 to-transparent', help_text='Tailwind gradient overlay (optional)', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
